<div class="checkout-agreements">
    <select name="ordermessage-topic" id="ordermessage-topic">
        <option disabled selected value>Choose topic</option>
        <?php
        foreach ($this->prepareTopics() as $row) {
            echo '<option value="'.$row['topic_id'].'">'.$row['topic'].'</option>';
        }
        ?>
    </select>
    <input type="text" placeholder="Your message" name="ordermessage-message" id="ordermessage-message"/>
</div>