<?php

foreach ($this->getQuestions() as $row) {
    $answers = $this->getResults($row['customerpoll_id']);

    $dataPoints = array(
        array("y" => $answers['yes'], "label" => "Yes"),
        array("y" => $answers['no'], "label" => "No")
    );
    ?>

    <?php echo '<div id="chartContainer' . $row['customerpoll_id'] . '" class="chart"></div>'; ?>

    <script>
        var chart<?php echo $row['customerpoll_id'] ?> = new CanvasJS.Chart("chartContainer<?php echo $row['customerpoll_id'] ?>", {
            animationEnabled: true,
            theme: "light2",
            title: {
                text: <?php echo json_encode($row['question']) ?>
            },
            data: [{
                type: "column",
                yValueFormatString: "#,##0.## tonnes",
                dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
            }]
        });
        chart<?php echo $row['customerpoll_id'] ?>.render();
    </script>

<?php } ?>