<?php

$questions = $this->getQuestions();
$ids = $this->getQuestionsIds();

foreach ($ids as $id) {
    $answers = $this->getResults($id);

    $dataPoints = array(
        array("y" => $answers['yes'], "label" => "Yes"),
        array("y" => $answers['no'], "label" => "No")
    );
    ?>

    <?php echo '<div id="chartContainer' . $id . '" class="chart"></div>'; ?>

    <script>
        var chart<?php echo $id ?> = new CanvasJS.Chart("chartContainer<?php echo $id ?>", {
            animationEnabled: true,
            theme: "light2",
            title: {
                text: <?php echo json_encode($questions[$id - 1]) ?>
            },
            data: [{
                type: "column",
                yValueFormatString: "#,##0.## tonnes",
                dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
            }]
        });
        chart<?php echo $id ?>.render();
    </script>

<?php } ?>