<script type="text/javascript">
    Review.prototype.save = Review.prototype.save.wrap(function(orig) {
        var form = $(this.agreementsForm) ? $(this.agreementsForm) : $(payment.form);
        if (form) {
            var message = $('ordermessage-message');
            var topic = $('ordermessage-topic');

            form.insert(message);
            form.insert(topic);
        }
        orig();
    });
</script>