<h3>Is our store performance good?</h3>
<!--//<form name="form" action="--><?php //Mage::getBaseUrl('') ?><!--[controller_first_name]/save" method="post"></form>-->
<form method="post">
    <label>
        <input type="radio" name="storepoll" value="yes" required> Yes
    </label>
    <label>
        <input type="radio" name="storepoll" value="no" required> No
    </label><br>
    <input type="submit" value="vote">
</form>
