<?php
$answers = $this->getResults();

$dataPoints = array(
    array("y" => $answers['yes'], "label" => "Yes" ),
    array("y" => $answers['no'], "label" => "No" )
);

?>
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2",
                title:{
                    text: "Poll: Is our store performance good?"
                },
                data: [{
                    type: "column",
                    yValueFormatString: "#,##0.## tonnes",
                    dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
                }]
            });
            chart.render();

        }
    </script>

<div id="chartContainer" style="height: 370px; width: 60%; margin:0 auto;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
