<?php

echo $this->myfunction();

Zend_Debug::dump(Mage::getUrl('customerpool/index'))

?>

Is our store performance good?
<!--//<form name="form" action="--><?php //Mage::getBaseUrl('') ?><!--[controller_first_name]/save" method="post"></form>-->
<form method="post" action="<?php Mage::getUrl('customerpoll/index') ?>">
    <label>
        <input type="radio" name="storepoll" value="yes" required> Yes
    </label>
    <label>
        <input type="radio" name="storepoll" value="no" required> No
    </label><br>
    <input type="submit" value="vote">
</form>
